env: standard
runtime: nodejs20
service: frontend

instance_class: F2
entrypoint: npm run start

handlers:
- url: /_next/static
  static_dir: build/static

- url: /.*
  script: auto

env_variables:
  NEXT_PUBLIC_API_URL: "https://ranking-app-bf2df.an.r.appspot.com/api"
  NEXT_PUBLIC_WEB_URL: "https://ranking-app-bf2df.an.r.appspot.com/"
  NEXT_PUBLIC_API_KEY: "iuhashfkuashefasiufhoasuefoaeasoiflfeas"

automatic_scaling:
  max_instances: 2
  min_instances: 0