import 'bootstrap/dist/css/bootstrap.min.css'
import { Inter } from "next/font/google";
import AuthProviderClient from "../components/AuthProviderClient";
import Header from "../components/Header";
import BootstrapClient from '@/components/BootstrapClient.js';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProviderClient>
          <Header />
          {children}
        </AuthProviderClient>
        <BootstrapClient />
      </body>
    </html>
  );
}
